# Generated by Django 4.1 on 2022-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('0', 'Superusuario'), ('1', 'Administrador')], max_length=1),
        ),
    ]
