# Generated by Django 4.1 on 2022-08-21 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_proyectos_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('proj_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyectos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto User',
                'verbose_name_plural': 'Proyecto Users',
            },
        ),
    ]
